//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinExifTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinExifTool.Properties.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to ExifTool.exe is not specified or ExifTool.exe is not found. ExifTool.exe is required for proper work. Point to the location of the file or download it if it has not been downloaded yet..
        /// </summary>
        internal static string exiftool_not_found {
            get {
                return ResourceManager.GetString("exiftool_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the metadata.
        /// </summary>
        internal static string metadata_not_read {
            get {
                return ResourceManager.GetString("metadata_not_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tagged:  {0}  /  {1}.
        /// </summary>
        internal static string tagged_files {
            get {
                return ResourceManager.GetString("tagged_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task canceled.
        /// </summary>
        internal static string task_canceled {
            get {
                return ResourceManager.GetString("task_canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start the task. Previous task is still running..
        /// </summary>
        internal static string task_still_running {
            get {
                return ResourceManager.GetString("task_still_running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct file modification.
        /// </summary>
        internal static string WorkClassCodepage_caption {
            get {
                return ResourceManager.GetString("WorkClassCodepage_caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert codepage.
        /// </summary>
        internal static string WorkClassCodepage_description {
            get {
                return ResourceManager.GetString("WorkClassCodepage_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codepage convertion is made directly as ExifTool command.  Do you want to continue?.
        /// </summary>
        internal static string WorkClassCodepage_warning {
            get {
                return ResourceManager.GetString("WorkClassCodepage_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set file modification date by Exif date.
        /// </summary>
        internal static string WorkClassExif_description {
            get {
                return ResourceManager.GetString("WorkClassExif_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed date.
        /// </summary>
        internal static string WorkClassFixedDate_description {
            get {
                return ResourceManager.GetString("WorkClassFixedDate_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move/copy metadata between IPTC/XMP fields.
        /// </summary>
        internal static string WorkClassMetadata_description {
            get {
                return ResourceManager.GetString("WorkClassMetadata_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set file modification date by filename (movies).
        /// </summary>
        internal static string WorkClassPattern_description {
            get {
                return ResourceManager.GetString("WorkClassPattern_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find pattern in the file name.
        /// </summary>
        internal static string WorkClassPattern_rowerror {
            get {
                return ResourceManager.GetString("WorkClassPattern_rowerror", resourceCulture);
            }
        }
    }
}
