//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinExifTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMdd_HHmmss")]
        public string patterns {
            get {
                return ((string)(this["patterns"]));
            }
            set {
                this["patterns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string exiftool {
            get {
                return ((string)(this["exiftool"]));
            }
            set {
                this["exiftool"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WorkClassExif")]
        public string lasttask {
            get {
                return ((string)(this["lasttask"]));
            }
            set {
                this["lasttask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string lang {
            get {
                return ((string)(this["lang"]));
            }
            set {
                this["lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesFILE {
            get {
                return ((bool)(this["gvPropertiesFILE"]));
            }
            set {
                this["gvPropertiesFILE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesEXIF {
            get {
                return ((bool)(this["gvPropertiesEXIF"]));
            }
            set {
                this["gvPropertiesEXIF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesIPTC {
            get {
                return ((bool)(this["gvPropertiesIPTC"]));
            }
            set {
                this["gvPropertiesIPTC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesXMP {
            get {
                return ((bool)(this["gvPropertiesXMP"]));
            }
            set {
                this["gvPropertiesXMP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gvPropertiesExcludedProperties {
            get {
                return ((string)(this["gvPropertiesExcludedProperties"]));
            }
            set {
                this["gvPropertiesExcludedProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime WorkClassFixedDate_Date {
            get {
                return ((global::System.DateTime)(this["WorkClassFixedDate_Date"]));
            }
            set {
                this["WorkClassFixedDate_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime WorkClassFixedDate_Shift {
            get {
                return ((global::System.DateTime)(this["WorkClassFixedDate_Shift"]));
            }
            set {
                this["WorkClassFixedDate_Shift"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorkClassFixedDate_ShiftChecked {
            get {
                return ((bool)(this["WorkClassFixedDate_ShiftChecked"]));
            }
            set {
                this["WorkClassFixedDate_ShiftChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int BATCHSIZE {
            get {
                return ((int)(this["BATCHSIZE"]));
            }
            set {
                this["BATCHSIZE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Miejsca:Barcelona|Miejsca:Lizbona|Miejsca:Porto|Miejsca:Słowacja|Miejsca:Czechy|M" +
            "iejsca:Polska|Miejsca:Kraków|Miejsca:Poznań|Tematy:Konie|Tematy:Żagle|Tematy:Mur" +
            "ale")]
        public string keywords {
            get {
                return ((string)(this["keywords"]));
            }
            set {
                this["keywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpeg|jpg|tif|tiff|png|dng|orf|nef|raw")]
        public string extensions {
            get {
                return ((string)(this["extensions"]));
            }
            set {
                this["extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesCHANGED {
            get {
                return ((bool)(this["gvPropertiesCHANGED"]));
            }
            set {
                this["gvPropertiesCHANGED"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool gvPropertiesMAIN {
            get {
                return ((bool)(this["gvPropertiesMAIN"]));
            }
            set {
                this["gvPropertiesMAIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IPTC:Keywords|File:FileCreateDate|File:FileModifyDate|IPTC:ObjectName|IPTC:Captio" +
            "n-Abstract|IPTC:City|IPTC:Headline|IPTC:Country-PrimaryLocationName|File:Comment" +
            "|XMP:Rating")]
        public string gvPropertiesMainProperties {
            get {
                return ((string)(this["gvPropertiesMainProperties"]));
            }
            set {
                this["gvPropertiesMainProperties"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.Forms.FormWindowState frmMain_WindowsState {
            get {
                return ((global::System.Windows.Forms.FormWindowState)(this["frmMain_WindowsState"]));
            }
            set {
                this["frmMain_WindowsState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMain_Location {
            get {
                return ((global::System.Drawing.Point)(this["frmMain_Location"]));
            }
            set {
                this["frmMain_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int frmMain_SplitDistance {
            get {
                return ((int)(this["frmMain_SplitDistance"]));
            }
            set {
                this["frmMain_SplitDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38")]
        public int frmMain_gvFiles_w1 {
            get {
                return ((int)(this["frmMain_gvFiles_w1"]));
            }
            set {
                this["frmMain_gvFiles_w1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int frmMain_gvFiles_w2 {
            get {
                return ((int)(this["frmMain_gvFiles_w2"]));
            }
            set {
                this["frmMain_gvFiles_w2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int frmMain_gvFiles_w3 {
            get {
                return ((int)(this["frmMain_gvFiles_w3"]));
            }
            set {
                this["frmMain_gvFiles_w3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int frmMain_gvFiles_w4 {
            get {
                return ((int)(this["frmMain_gvFiles_w4"]));
            }
            set {
                this["frmMain_gvFiles_w4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int frmMain_gvFiles_w5 {
            get {
                return ((int)(this["frmMain_gvFiles_w5"]));
            }
            set {
                this["frmMain_gvFiles_w5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int frmMain_gvFiles_w6 {
            get {
                return ((int)(this["frmMain_gvFiles_w6"]));
            }
            set {
                this["frmMain_gvFiles_w6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int frmMain_gvFiles_w7 {
            get {
                return ((int)(this["frmMain_gvFiles_w7"]));
            }
            set {
                this["frmMain_gvFiles_w7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int frmMain_gvFiles_w8 {
            get {
                return ((int)(this["frmMain_gvFiles_w8"]));
            }
            set {
                this["frmMain_gvFiles_w8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int frmMain_gvFiles_w9 {
            get {
                return ((int)(this["frmMain_gvFiles_w9"]));
            }
            set {
                this["frmMain_gvFiles_w9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int frmMain_gvFiles_w10 {
            get {
                return ((int)(this["frmMain_gvFiles_w10"]));
            }
            set {
                this["frmMain_gvFiles_w10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GOOGLE_APIKEY {
            get {
                return ((string)(this["GOOGLE_APIKEY"]));
            }
            set {
                this["GOOGLE_APIKEY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52.24 N, 19.84 E")]
        public string frmMap_LastPos {
            get {
                return ((string)(this["frmMap_LastPos"]));
            }
            set {
                this["frmMap_LastPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public int frmMap_LastZoom {
            get {
                return ((int)(this["frmMap_LastZoom"]));
            }
            set {
                this["frmMap_LastZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GoogleMapProvider")]
        public string MapProvider {
            get {
                return ((string)(this["MapProvider"]));
            }
            set {
                this["MapProvider"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editFrom1 {
            get {
                return ((int)(this["WorkClassMetadata_editFrom1"]));
            }
            set {
                this["WorkClassMetadata_editFrom1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editFrom2 {
            get {
                return ((int)(this["WorkClassMetadata_editFrom2"]));
            }
            set {
                this["WorkClassMetadata_editFrom2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editFrom3 {
            get {
                return ((int)(this["WorkClassMetadata_editFrom3"]));
            }
            set {
                this["WorkClassMetadata_editFrom3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editFrom4 {
            get {
                return ((int)(this["WorkClassMetadata_editFrom4"]));
            }
            set {
                this["WorkClassMetadata_editFrom4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editTo1 {
            get {
                return ((int)(this["WorkClassMetadata_editTo1"]));
            }
            set {
                this["WorkClassMetadata_editTo1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editTo2 {
            get {
                return ((int)(this["WorkClassMetadata_editTo2"]));
            }
            set {
                this["WorkClassMetadata_editTo2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editTo3 {
            get {
                return ((int)(this["WorkClassMetadata_editTo3"]));
            }
            set {
                this["WorkClassMetadata_editTo3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int WorkClassMetadata_editTo4 {
            get {
                return ((int)(this["WorkClassMetadata_editTo4"]));
            }
            set {
                this["WorkClassMetadata_editTo4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkClassMetadata_cb1 {
            get {
                return ((bool)(this["WorkClassMetadata_cb1"]));
            }
            set {
                this["WorkClassMetadata_cb1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkClassMetadata_cb2 {
            get {
                return ((bool)(this["WorkClassMetadata_cb2"]));
            }
            set {
                this["WorkClassMetadata_cb2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkClassMetadata_cb3 {
            get {
                return ((bool)(this["WorkClassMetadata_cb3"]));
            }
            set {
                this["WorkClassMetadata_cb3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WorkClassMetadata_cb4 {
            get {
                return ((bool)(this["WorkClassMetadata_cb4"]));
            }
            set {
                this["WorkClassMetadata_cb4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WorkClassFixedDate_Exif {
            get {
                return ((bool)(this["WorkClassFixedDate_Exif"]));
            }
            set {
                this["WorkClassFixedDate_Exif"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WorkClassCodepage_editFrom {
            get {
                return ((int)(this["WorkClassCodepage_editFrom"]));
            }
            set {
                this["WorkClassCodepage_editFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int WorkClassCodepage_editTo {
            get {
                return ((int)(this["WorkClassCodepage_editTo"]));
            }
            set {
                this["WorkClassCodepage_editTo"] = value;
            }
        }
    }
}
